# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M9xaCmqBMY4QtK3UF4Iy0eelgyN9vlkj
"""

import requests
from bs4 import BeautifulSoup

url = 'https://www.usatoday.com/'

links = []
website = requests.get(url)
website_text = website.text
soup = BeautifulSoup(website_text)

for link in soup.find_all('a', href=True):
    links.append(link.get('href'))


for url in links:
  print(link)